name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      attestations: write
      artifact-metadata: write
      contents: read
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Required for Nerdbank.GitVersioning

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x

      - uses: dotnet/nbgv@v0.5
        id: nbgv

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release /p:ContinuousIntegrationBuild=true

      # https://tunit.dev/docs/guides/html-report/#enabling-automatic-artifact-upload
      - name: Expose GitHub Actions Runtime
        uses: actions/github-script@v8
        with:
          script: |
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN']);
            core.exportVariable('ACTIONS_RESULTS_URL', process.env['ACTIONS_RESULTS_URL']);

      - name: Test
        # --no-build leads to empty coverage
        run: dotnet test -c Release --coverage --coverage-output cobertura.xml --coverage-output-format cobertura --results-directory .

      - name: Upload coverage reports to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Pack
        if: matrix.os == 'ubuntu-latest'
        run: dotnet pack src/DirectoryPackagesPropsUpdater -c Release --no-build -o ./artifacts

      - name: Upload NuGet package
        if: matrix.os == 'ubuntu-latest'
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: |
            ./artifacts/*.nupkg
            ./artifacts/*.snupkg

      - uses: actions/attest-build-provenance@v3
        if: matrix.os == 'ubuntu-latest'
        with:
          subject-name: nupkg
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}